"""remove has_avatar from users

Revision ID: 0d7ccc211194
Revises: c5eb863f27b9
Create Date: 2026-05-09 03:58:20.058790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0d7ccc211194"
down_revision: Union[str, Sequence[str], None] = "c5eb863f27b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "has_avatar")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "has_avatar", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
